import { invokeLLM } from "../_core/llm";
import { generateImage } from "../_core/imageGeneration";
import type { BrandGuidelines } from "./brandBrain";

/**
 * Character archetype generated by AI
 */
export interface CharacterArchetype {
  id: string;
  name: string;
  description: string;
  personality: string;
  targetAudience: string;
  archetypeType: string;
  visualDescription: string;
  brandAlignment: number; // 0-100
  reasoning: string;
  imageUrl?: string;
  variants: CharacterVariant[];
}

/**
 * Visual variant of a character archetype
 */
export interface CharacterVariant {
  id: string;
  imageUrl: string;
  description: string;
  style: string;
  confidence: number;
  generatedAt: Date;
}

/**
 * Generate multiple character archetypes based on brand guidelines
 * Analyzes brand identity and creates 3-5 distinct character concepts
 */
export async function generateCharacterArchetypes(
  brand: BrandGuidelines,
  productDescription: string,
  count: number = 4
): Promise<CharacterArchetype[]> {
  try {
    // Use LLM to generate character archetypes based on brand
    const response = await invokeLLM({
      messages: [
        {
          role: "system",
          content: `You are a creative director specializing in brand character development. 
          Generate compelling character archetypes that embody the brand's identity and appeal to the target audience.
          Each archetype should be unique, memorable, and aligned with the brand's mission and aesthetic.
          Return a JSON array of character concepts.`,
        },
        {
          role: "user",
          content: `Create ${count} distinct character archetypes for this brand:
          
Brand Name: ${brand.name || "Unknown"}
Target Customer: ${brand.targetCustomer || "General audience"}
Aesthetic: ${brand.aesthetic || "Modern"}
Mission: ${brand.mission || "Inspire and delight"}
Core Messaging: ${brand.coreMessaging || "Quality and innovation"}
Product: ${productDescription}

For each archetype, provide:
1. Name (e.g., "The Visionary Entrepreneur", "The Artisan's Muse")
2. Personality traits (3-4 key traits)
3. Visual description (clothing, appearance, vibe)
4. Why they align with the brand
5. Target audience appeal

Return as JSON array with structure: {name, personality, visualDescription, reasoning, targetAudience, archetypeType}`,
        },
      ],
      response_format: {
        type: "json_schema",
        json_schema: {
          name: "character_archetypes",
          strict: true,
          schema: {
            type: "object",
            properties: {
              archetypes: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    name: { type: "string" },
                    personality: { type: "string" },
                    visualDescription: { type: "string" },
                    reasoning: { type: "string" },
                    targetAudience: { type: "string" },
                    archetypeType: { type: "string" },
                  },
                  required: [
                    "name",
                    "personality",
                    "visualDescription",
                    "reasoning",
                    "targetAudience",
                    "archetypeType",
                  ],
                  additionalProperties: false,
                },
              },
            },
            required: ["archetypes"],
            additionalProperties: false,
          },
        },
      },
    });

    const content = response.choices[0].message.content;
    if (!content) throw new Error("No response from LLM");

    const parsed = JSON.parse(typeof content === "string" ? content : JSON.stringify(content));
    const archetypes: CharacterArchetype[] = [];

    for (const arch of parsed.archetypes) {
      const archetype: CharacterArchetype = {
        id: `archetype_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        name: arch.name,
        description: arch.personality,
        personality: arch.personality,
        targetAudience: arch.targetAudience,
        archetypeType: arch.archetypeType,
        visualDescription: arch.visualDescription,
        brandAlignment: calculateBrandAlignment(arch, brand),
        reasoning: arch.reasoning,
        variants: [],
      };

      // Generate initial image for archetype
      try {
        const imageResult = await generateImage({
          prompt: `Create a professional portrait of a character: ${arch.name}. 
          Style: ${brand.aesthetic || "modern"}. 
          Appearance: ${arch.visualDescription}. 
          Mood: ${brand.mission || "professional"}. 
          High quality, cinematic lighting, professional photography.`,
        });

        if (imageResult.url) {
          archetype.imageUrl = imageResult.url;
          archetype.variants.push({
            id: `variant_${Date.now()}_0`,
            imageUrl: imageResult.url,
            description: "Primary variant",
            style: brand.aesthetic || "modern",
            confidence: 85,
            generatedAt: new Date(),
          });
        }
      } catch (error) {
        console.error(`Failed to generate image for ${arch.name}:`, error);
      }

      archetypes.push(archetype);
    }

    return archetypes;
  } catch (error) {
    console.error("Failed to generate character archetypes:", error);
    throw new Error(`Character archetype generation failed: ${error instanceof Error ? error.message : String(error)}`);
  }
}

/**
 * Generate additional visual variants for a character archetype
 * Keeps the same character concept but varies the visual representation
 */
export async function generateCharacterVariants(
  archetype: CharacterArchetype,
  brand: BrandGuidelines,
  count: number = 3
): Promise<CharacterVariant[]> {
  const variants: CharacterVariant[] = [];

  const styles = [
    "cinematic photography",
    "illustrated art style",
    "professional headshot",
    "candid lifestyle",
    "dramatic lighting",
  ];

  for (let i = 0; i < Math.min(count, styles.length); i++) {
    try {
      const imageResult = await generateImage({
        prompt: `Create a portrait of ${archetype.name} in ${styles[i]} style.
        Character: ${archetype.visualDescription}
        Brand aesthetic: ${brand.aesthetic || "modern"}
        Mood: ${archetype.personality}
        Professional quality, consistent character appearance.`,
      });

      if (imageResult.url) {
        variants.push({
          id: `variant_${Date.now()}_${i + 1}`,
          imageUrl: imageResult.url,
          description: `${styles[i]} variant`,
          style: styles[i],
          confidence: 80 + Math.random() * 15,
          generatedAt: new Date(),
        });
      }
    } catch (error) {
      console.error(`Failed to generate variant ${i + 1}:`, error);
    }
  }

  return variants;
}

/**
 * Retake a character variant - generate a new image while keeping the archetype
 */
export async function retakeCharacterImage(
  archetype: CharacterArchetype,
  brand: BrandGuidelines,
  style?: string
): Promise<CharacterVariant | null> {
  try {
    const selectedStyle = style || "professional cinematic photography";

    const imageResult = await generateImage({
      prompt: `Create a new portrait of ${archetype.name} in ${selectedStyle} style.
      Character: ${archetype.visualDescription}
      Personality: ${archetype.personality}
      Brand aesthetic: ${brand.aesthetic || "modern"}
      Professional quality, consistent character, fresh perspective.`,
    });

    if (imageResult.url) {
      return {
        id: `variant_${Date.now()}_retake`,
        imageUrl: imageResult.url,
        description: `Retake - ${selectedStyle}`,
        style: selectedStyle,
        confidence: 85,
        generatedAt: new Date(),
      };
    }
  } catch (error) {
    console.error("Failed to retake character image:", error);
  }

  return null;
}

/**
 * Calculate how well a character aligns with brand guidelines
 */
function calculateBrandAlignment(archetype: Record<string, unknown>, brand: BrandGuidelines): number {
  let score = 50; // Base score

  // Check alignment with target customer
  if (archetype.targetAudience?.toLowerCase().includes(brand.targetCustomer?.toLowerCase())) {
    score += 15;
  }

  // Check aesthetic alignment
  if (archetype.visualDescription?.toLowerCase().includes(brand.aesthetic?.toLowerCase())) {
    score += 15;
  }

  // Check mission alignment
  if (archetype.reasoning?.toLowerCase().includes(brand.mission?.toLowerCase())) {
    score += 10;
  }

  // Check messaging alignment
  if (archetype.personality?.toLowerCase().includes(brand.coreMessaging?.toLowerCase())) {
    score += 10;
  }

  return Math.min(100, Math.max(0, score));
}

/**
 * Select a hero character for the campaign
 * This becomes the primary character used across all generated content
 */
export interface HeroCharacter {
  id: string;
  archetypeId: string;
  selectedVariantId: string;
  name: string;
  imageUrl: string;
  selectedAt: Date;
  usageCount: number;
  consistency: number; // How consistently this character appears across content
}

/**
 * Create a hero character from an archetype and variant
 */
export function createHeroCharacter(
  archetype: CharacterArchetype,
  variantId: string
): HeroCharacter | null {
  const variant = archetype.variants.find((v) => v.id === variantId);
  if (!variant) return null;

  return {
    id: `hero_${Date.now()}`,
    archetypeId: archetype.id,
    selectedVariantId: variantId,
    name: archetype.name,
    imageUrl: variant.imageUrl,
    selectedAt: new Date(),
    usageCount: 0,
    consistency: 100,
  };
}
