steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-film-studio:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ai-film-studio:latest'
      - '.'
    timeout: 1200s

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-film-studio:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ai-film-studio:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-film-studio'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ai-film-studio:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--add-cloudsql-instances'
      - 'ai-film-studio-485900:us-central1:ai-film-studio-db'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,BUILT_IN_FORGE_API_KEY=GEMINI_API_KEY:latest,NANOBANANA_API_KEY=NANOBANANA_API_KEY:latest,SORA_API_KEY=SORA_API_KEY:latest,VEO3_API_KEY=VEO3_API_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/ai-film-studio:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ai-film-studio:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s


